FROM homebrew/brew

ENV HOMEBREW_NO_ENV_FILTERING=1
ENV HOMEBREW_NO_AUTO_UPDATE=1
ENV HOMEBREW_NO_ANALYTICS=1
ENV HOMEBREW_NO_EMOJI=1
ENV HOMEBREW_COLOR=1

COPY main.rb /

ENTRYPOINT ["brew", "ruby", "/main.rb"]
