name: Close Pull Request

on:
  pull_request:
    types:
      - opened
    paths:
      - "Formula/*.rb"

concurrency:
  group: close-pr
  cancel-in-progress: false

jobs:
  close-pr:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false

      - name: Delete
        env:
          BRANCH: ${{github.event.pull_request.head.ref}}
        run: git push origin --delete "$BRANCH"
