name: Close Pull Request

on:
  pull_request:
    types:
      - opened
    paths:
      - "Formula/*.rb"

concurrency:
  group: close-pr
  cancel-in-progress: false

jobs:
  close-pr:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Delete
        env:
          GH_TOKEN: ${{github.token}}
          BRANCH: ${{github.event.pull_request.head.ref}}
        run: gh api -X DELETE "repos/$GITHUB_REPOSITORY/git/refs/heads/$BRANCH"
